### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by Dudrie** [Knils/atom-tabletopsimulator-lua#1]
Steps to reproduce:

1. Import Tabletop Scripts LUA Scripts with the package
2. "Save and play" the script while having an empty editor open

**Atom Version**: 1.6.2
**System**: SASCHA-PC
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package, v1.0.0

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At C:\Users\Sascha\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1049

Error: Can't save buffer with no file path
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Sascha\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1049:15)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Sascha\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Sascha\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:629:26)
    at Object.module.exports.TabletopsimulatorLua.saveAndPlay (file:///C:/Users/Sascha/.atom/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:133:14)
    at atom-workspace.subscriptions.add.atom.commands.add.tabletopsimulator-lua:saveAndPlay (file:///C:/Users/Sascha/.atom/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:91:101)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Sascha\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Sascha\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Sascha\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Sascha\AppData\Local\atom\app-1.6.2\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -1:40.5.0 application:new-file (atom-pane.pane.active)
     -1:22.8.0 tabletopsimulator-lua:getObjects (atom-text-editor.editor.is-focused)
     -1:13.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:08.0 tabletopsimulator-lua:saveAndPlay (atom-text-editor.editor.is-focused)
  2x -0:18.6.0 tabletopsimulator-lua:getObjects (a.stack-toggle)
     -0:02.8.0 tabletopsimulator-lua:saveAndPlay (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.2.10
tabletopsimulator-lua, v1.0.0

# Dev
No dev packages
```

**Comment by tranek** [comment]
I can only reproduce this error when I have an "untitled" new tab open. I'll throw it in a try/catch. Thanks for reporting.

**Comment by Dudrie** [comment]
Yeah. I should have added that the tab was untitled - sorry have forgotten about that detail.

**Comment by tranek** [comment]
It's all good. A simple try/catch around the editor.save() call fixed the problem. Thanks!
