### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Kippiii** [Knils/atom-tabletopsimulator-lua#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 1.1.7

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:731

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at Object.saveAndPlay (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:200:30)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:96:101)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -8:16.5.0 tabletopsimulator-lua:saveAndPlay (input.hidden-input)
     -5:48.7.0 tabletopsimulator-lua:getObjects (input.hidden-input)
     -4:10.2.0 core:backspace (input.hidden-input)
     -4:08.6.0 core:confirm (input.hidden-input)
 50x -2:43.1.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:36.7.0 tabletopsimulator-lua:saveAndPlay (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
tabletopsimulator-lua 1.1.7 
```

**Comment by admor2** [comment]
Is there a fix for this? really want to use ATOM for my project.

**Comment by Kippiii** [comment]
The problem for me was the I had added files to the directory, causing Atom to be unable to sync those random files to TTS. Try deleting all current files in your Atom.

**Comment by admor2** [comment]
@Kippiii  Thank you very much.
