### ISSUE TITLE
Failed to load the tabletopsimulator-lua package

### ISSUE THREAD

**Issue by stolencatkarma** [Knils/atom-tabletopsimulator-lua#4]
Failed to load the tabletopsimulator-lua package
Cannot find module 'mkdirp'

Error: Cannot find module 'mkdirp'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/andrew/.atom/packages/atom-tabletopsimulator-lua-master/lib/tabletopsimulator-lua.coffee:8:10)
    at Object.<anonymous> (/home/andrew/.atom/packages/atom-tabletopsimulator-lua-master/lib/tabletopsimulator-lua.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:397:19)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:743:28

**Comment by stolencatkarma** [comment]
apt-get install nodejs-mkdirp 

does not fix it

**Comment by onelivesleft** [comment]
I realise this is a really old post, but I just ran into this exact problem. The fix is to install node.js (https://nodejs.org/en/), then before (or after) you type 'apm link' in a command prompt type 'npm install mkdirp'
