### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by GiantDwarf01** [Knils/atom-tabletopsimulator-lua#47]
[Enter steps to reproduce:]

1. Just was typing, filling in table values, and it drops when clicking within a certain range of characters on a line

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tabletopsimulator-lua](https://github.com/Knils/atom-tabletopsimulator-lua) package 10.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At C:\Users\*********\AppData\Local\atom\app-1.23.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:948

TypeError: Cannot read property '1' of null
    at Object.cursorChangeEvent (/packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:687:89)
    at /packages/tabletopsimulator-lua/lib/tabletopsimulator-lua.coffee:587:10
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.cursorMoved (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:2687:31)
    at Selection.markerDidChange (~/AppData/Local/atom/app-1.23.1/resources/app/src/selection.js:914:25)
    at Selection.marker.onDidChange.e (~/AppData/Local/atom/app-1.23.1/resources/app/src/selection.js:21:45)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at ~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/marker.js:428:26)
    at Marker.module.exports.Marker.update (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/marker.js:369:18)
    at Marker.module.exports.Marker.setHeadPosition (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/marker.js:144:25)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/display-marker.js:146:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/display-marker.js:154:25)
    at changePosition (~/AppData/Local/atom/app-1.23.1/resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (~/AppData/Local/atom/app-1.23.1/resources/app/src/cursor.js:713:11)
    at Cursor.setScreenPosition (~/AppData/Local/atom/app-1.23.1/resources/app/src/cursor.js:67:16)
    at moveCursors.cursor (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:2491:52)
    at Array.forEach (native)
    at transact (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:2681:31)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextEditor.transact (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:2680:23)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:2491:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor-component.js:1810:25)
```

### Commands

```
     -1:46.6.0 core:backspace (input.hidden-input)
  2x -1:46.1.0 core:move-right (input.hidden-input)
     -1:45.6.0 core:move-down (input.hidden-input)
     -1:44.9.0 core:move-left (input.hidden-input)
     -1:44.5.0 core:move-down (input.hidden-input)
  5x -1:44.1.0 core:move-right (input.hidden-input)
     -1:33.9.0 core:move-left (input.hidden-input)
     -0:59 core:delete (input.hidden-input)
 34x -0:58.6.0 core:move-right (input.hidden-input)
     -0:56 core:move-up (input.hidden-input)
  2x -0:55.5.0 core:move-down (input.hidden-input)
     -0:33.3.0 core:move-left (input.hidden-input)
  8x -0:32.8.0 core:move-right (input.hidden-input)
     -0:23.3.0 core:backspace (input.hidden-input)
  2x -0:22.6.0 core:move-right (input.hidden-input)
     -0:21.2.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-pointfree 0.2.0 
ide-haskell-hasktags 0.0.12 
ide-haskell-profiteurjs 0.0.2 
language-haskell-scoped 0.1.0 
tabletopsimulator-lua 10.2.0 
```

**Comment by onelivesleft** [comment]
Fix for this will be released soon; in the mean time if you untick the 'Highlight GUID object in TTS' setting you'll stop it occurring.
